### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by ngahchi** [yasirkula/UnityNativeCamera#1]
Undefined symbols for architecture arm64:
  "__NativeCamera_IsCameraBusy", referenced from:
      _NCCameraCallbackiOS__NativeCamera_IsCameraBusy_m2801708894 in Bulk_Assembly-CSharp-firstpass_0.o
      _NCCameraCallbackiOS_Update_m1233421003 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NCCameraCallbackiOS__NativeCamera_IsCameraBusy_m2801708894)
  "__NativeCamera_LoadImageAtPath", referenced from:
      _NativeCamera__NativeCamera_LoadImageAtPath_m1353718599 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeCamera__NativeCamera_LoadImageAtPath_m1353718599)
  "__NativeCamera_RecordVideo", referenced from:
      _NativeCamera__NativeCamera_RecordVideo_m2562012664 in Bulk_Assembly-CSharp-firstpass_0.o
      _NativeCamera_RecordVideo_m655095076 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeCamera__NativeCamera_RecordVideo_m2562012664)
  "__NativeCamera_TakePicture", referenced from:
      _NativeCamera__NativeCamera_TakePicture_m1100368309 in Bulk_Assembly-CSharp-firstpass_0.o
      _NativeCamera_TakePicture_m3934588882 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeCamera__NativeCamera_TakePicture_m1100368309)
  "__NativeCamera_OpenSettings", referenced from:
      _NativeCamera__NativeCamera_OpenSettings_m3534565788 in Bulk_Assembly-CSharp-firstpass_0.o
      _NativeCamera_OpenSettings_m3107873246 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeCamera__NativeCamera_OpenSettings_m3534565788)
  "__NativeCamera_HasCamera", referenced from:
      _NativeCamera__NativeCamera_HasCamera_m489295455 in Bulk_Assembly-CSharp-firstpass_0.o
      _NativeCamera_DeviceHasCamera_m2764571657 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeCamera__NativeCamera_HasCamera_m489295455)
  "__NativeCamera_RequestPermission", referenced from:
      _NativeCamera__NativeCamera_RequestPermission_m884264195 in Bulk_Assembly-CSharp-firstpass_0.o
      _NativeCamera_RequestPermission_m1003643796 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeCamera__NativeCamera_RequestPermission_m884264195)
  "__NativeCamera_GetImageProperties", referenced from:
      _NativeCamera__NativeCamera_GetImageProperties_m3227823442 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeCamera__NativeCamera_GetImageProperties_m3227823442)
  "__NativeCamera_CanOpenSettings", referenced from:
      _NativeCamera__NativeCamera_CanOpenSettings_m1091903706 in Bulk_Assembly-CSharp-firstpass_0.o
      _NativeCamera_CanOpenSettings_m1108638819 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeCamera__NativeCamera_CanOpenSettings_m1091903706)
  "__NativeCamera_CheckPermission", referenced from:
      _NativeCamera__NativeCamera_CheckPermission_m4225126317 in Bulk_Assembly-CSharp-firstpass_0.o
      _NativeCamera_CheckPermission_m2108779236 in Bulk_Assembly-CSharp-firstpass_0.o
     (maybe you meant: _NativeCamera__NativeCamera_CheckPermission_m4225126317)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by yasirkula** [comment]
Is _NativeCamera.mm_ correctly exported to your Xcode project, i.e. when you search for the file in Xcode's Project view, does it hit any results? If not, when you inspect NativeCamera.mm in Unity, is _iOS_ selected in "Select platforms for plugin"?

**Comment by ngahchi** [comment]
No NativeCamera.mm in Xcode Project.
iOS is selected in "Select platforms for plugin in Unity.

**Comment by yasirkula** [comment]
That's unexpected behaviour. What is your Unity version?

**Comment by ngahchi** [comment]
2017.3.1p3

**Comment by yasirkula** [comment]
P.S. Do you have any editor scripts with `[PostProcessBuild]` attribute in your project, other than _NCPostProcessBuild.cs_? It is very unlikely but a plugin may be preventing NativeCamera.mm from being exported in its post processor.

**Comment by ngahchi** [comment]
Try to rebuild unity project, a message is popup, click "Apply", then ios complie ok!
![image](https://user-images.githubusercontent.com/15306866/39872176-c35ab072-5499-11e8-8760-9d837303446f.png)
Thanks for your great plugin and support !!!
