### ISSUE TITLE
Is it possible to turn on video in preview mode, not saving acquired video frames?

### ISSUE THREAD

**Issue by vanIvan** [yasirkula/UnityNativeCamera#10]
Hello, I have need to acquire pointer / access to underlying camera buffer to make hard AI computations on acquired frame, I do need to do it in real time and have no need to store any data in Persistent storage. Can you tell if it is possible with your plugin, or it can be easily extended to handle such need. 

Thank you

**Comment by yasirkula** [comment]
Unfortunately not. NativeCamera launches the native camera app to take pictures/record videos, i.e. it doesn't render the camera feed in Unity or has any access to the camera feed.
