### ISSUE TITLE
Camera permission is always Denied after updating plugin from legacy version

### ISSUE THREAD

**Issue by novavision** [yasirkula/UnityNativeCamera#101]
**Description of the bug**

`NativeCamera.CheckPermission` always returns Denied in both cases:
1. before even asking the permission
2. after the permission is granted and app has a camera cotnrol

**Reproduction steps**

1. install legacy plugin using .unitypackage
2. follow the steps adding entries to AndroidManifest.xml
3. build apk
4. remove NativeCamera from Assets/Plugins directory
5. install latest plugin version addint git url to manifest.json
6. build apk - bug appears

On iOS devices everything works fine.

- Unity version: 2021.3.17
- Platform: Android
- Device: Xiaomi K20Pro
- How did you download the plugin: GitHub

**Additional info**

I did a clean project test and plugin camera permission worked fine there on the same Android device. I checked the AndroidManifest and compared it to my real project AndroidManifest - I found there <provider> tags which had to be removed (as I understood from the documentation). Somehow it was cached even aftere removing the plugin.
I removed Library and Temp folders and reimported project. These entries has gone and AndroidManifest looks almost the same as in the clean project. However the bug still exists.

Have no idea what's wrong there.

**Comment by yasirkula** [comment]
If you had imported the plugin to your actual project a while ago, could you update it to the latest version? Note that you no longer need to modify the AndroidManifest in any way.

**Comment by novavision** [comment]
@yasirkula that what I described in issue...

**Comment by yasirkula** [comment]
The "com.yasirkula.unity.NativeCameraContentProvider" entry must exist there yeah. It doesn't say anywhere that it shouldn't exist. Instead, you should check which of the READ_EXTERNAL_STORAGE, CAMERA (optional) and WRITE_EXTERNAL_STORAGE permissions are declared there.

**Comment by novavision** [comment]
I just followed the FAQ recommendation adding `WRITE_EXTERNAL_STORAGE`
Checked final manifest and 
`<uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` 
exist there. However I still always got Denied

**Comment by yasirkula** [comment]
NativeCamera also asks for storage permission on Android 12 or earlier because camera apps save the image to the gallery rather than the path we've provided (it's Android ecosystem, we dare not question it...). That path can't be accessed without storage permission.

Perhaps the storage permission dialog had shown up before installing NativeCamera (don't know which plugin added it beforehand) and you've selected "Deny-Don't ask again" while rejecting it. Then, after installing NativeCamera, the permission dialog isn't asked because "Don't ask again" was selected in a previous session. If that's indeed the case, then uninstalling and then reinstalling the app should resolve the issue.

**Comment by novavision** [comment]
That's not that case for sure because I already reinstalled the app tons of time.
Also, I see that clean project where permission request shows proper value has no Camera permission in app settings, only Storage permission

**Comment by novavision** [comment]
And another note - I tried to check the permission status usign Unity method 
`Android.Permission.RequestUserPermission` and it shows me proper value

**Comment by yasirkula** [comment]
The Camera permission is asked only if it's manually declared in AndroidManifest. That's an optional permission so it won't be asked if it's missing.

Can you replace [this line](https://github.com/yasirkula/UnityNativeCamera/blob/fd8dcbbac53a54e9f568368f47eaa3b4823854a6/Plugins/NativeCamera/NativeCamera.cs#L182) as follows: `AJC.CallStatic( "RequestPermission", Context, nativeCallback, isPicturePermission, (int) Permission.ShouldAsk );`

**Comment by novavision** [comment]
I can't edit the file if plugin downloaded by a package manager

**Comment by yasirkula** [comment]
Hmm, then I really don't know why it returns Denied on your project but not on a new project 😞 

NativeCamera asks both Gallery and Camera access. Unless you do the same with Unity's permission API, you'll only see the permission that you're asking.

https://github.com/yasirkula/UnityNativeCamera/blob/fd8dcbbac53a54e9f568368f47eaa3b4823854a6/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity/NativeCameraPermissionFragment.java#L61-L82

**Comment by novavision** [comment]
I assume AR Foundation (AR Core) somehow may affect it, but in my case I disable ARSession on Awake and enable it only after permission granted. This prevents AR foudnation request that camera permission automatically and lets me control it. 

Anyway, seems it's not the best option to use this plugin for my case - 2 requests instead of 1 is not what I need for sure.

Thanks for the support

**Comment by yasirkula** [comment]
And thank you for trying to debug this issue and providing all the useful information 🙂
