### ISSUE TITLE
LoadImagefromPathAsync example code

### ISSUE THREAD

**Issue by jinincarnate** [yasirkula/UnityNativeCamera#103]
Hi can u give a sample code on how to use the async version of LoadImagefromPath

**Comment by yasirkula** [comment]
Sure! Instead of `Texture2D texture = NativeCamera.LoadImageAtPath( path, maxSize );`, you should call `Texture2D texture = await NativeCamera.LoadImageAtPathAsync( path, maxSize );` in an **async** function.
