### ISSUE TITLE
After adjusting the resolution, the screen will be blurred

### ISSUE THREAD

**Issue by USSTJerry** [yasirkula/UnityNativeCamera#108]
first:After adjusting the resolution, the screen will be blurred   1600*  1200 and 640*  480 is fit for my device. The screen will be blurred 
in other resolution.

second: I perform streaming operations in 1600*  1200  , The local camera will get stuck. but  I perform streaming operations in 640  *480，The local camera will not get stuck  (push stream use third part sdk.（Two manufacturers）)

because the second question ,so i try the first solution，so i can not  adjust the resolution correctly

**Comment by yasirkula** [comment]
I don't think these issues can be resolved because camera app has full control over its own behaviour (resolution, blurriness, etc). All NativeCamera does is that it launches the camera app, tells it to take a picture/record a video, and wait until the camera app returns a simple "string filePath" of the resulting file.

**Comment by USSTJerry** [comment]
After adjusting the resolution, the screen will show correctly in 1600* 1200 and 640* 480 for my device. The screen will be blurred
in other resolution.

**Comment by USSTJerry** [comment]
1、i use that  one native camera push stream（1600 * 1200 sinlge）by one camera data, local native camera get stuck
, but i push stream (640 * 480 single) by using two native camera contact data,   local native camera do not get stuck.   

2、i use push stream(1600 * 1600 single) by WebCamTexture，local WebCamTexture do not get stuck, because i need two camera， so i need play two cameras, but WebCamTexture do not support to open two camera at the same time .


can you give me some suggestions ? thank you

**Comment by yasirkula** [comment]
NativeCamera doesn't access the camera stream. Its source code is actually quite simple, you can check it out here: https://github.com/yasirkula/UnityNativeCamera/tree/master/.github/AAR%20Source%20(Android)/java/com/yasirkula/unity

**Comment by USSTJerry** [comment]
ok ,thanks
