### ISSUE TITLE
Can i use the torch and the camera at the same time?

### ISSUE THREAD

**Issue by MSevillaPlatea** [yasirkula/UnityNativeCamera#11]
First of all, super cool repos you have here!

Second, i have seen this asset and I have a question, can i use the torch and the camera at the same time?

Thanks

**Comment by yasirkula** [comment]
Do you mean camera's flashlight? If so, you should be able to toggle the flashlight from the camera's user interface. For now, there is no way to enable/disable the flashlight programmatically.

**Comment by MSevillaPlatea** [comment]
Yes sorry the confusion, searching for this aparently the device function its called torch instead of flashlight. Im making an QR scanner using the camera with the texture.camera method but it seems that I cannot use the flashlight (or torch) at the same time and ive been looking for a work around.

**Comment by yasirkula** [comment]
Hmm, I don't think NativeCamera can help you with that issue :/

**Comment by MSevillaPlatea** [comment]
Thanks anyway!
