### ISSUE TITLE
Can't Record a Video Error: Can't find ContentProvider, camera is inaccessible!

### ISSUE THREAD

**Issue by CARIVASH** [yasirkula/UnityNativeCamera#12]
Hi, when I run the function RecordVideo my phone freeze, and I have to finish the app, it's something extra that I need to do? or I have to configure something in the code, thanks.

`private void RecordVideo(){
        NativeCamera.Permission permission = NativeCamera.RecordVideo((path) => {
            if(path != null){
                Handheld.PlayFullScreenMovie("file://"+path);
            }
        });
    }`

**Comment by CARIVASH** [comment]
in Assets/Plugins/Android

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.unity3d.player" android:installLocation="preferExternal" android:versionCode="1" android:versionName="1.0">
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="com.android.launcher.permission.READ_SETTINGS" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.CALL_PHONE" />
  <uses-permission android:name="android.permission.WRITE_SETTINGS" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.READ_SYNC_SETTINGS" />
  <application android:theme="@android:style/Theme.NoTitleBar.Fullscreen" android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="true"  >
  <provider android:name="com.yasirkula.unity.UnitySSContentProvider" android:authorities="MY_PACKAGE_NAME" android:exported="false" android:grantUriPermissions="true" />
        <service android:name="com.google.android.gms.analytics.CampaignTrackingService" />
    <receiver android:name="com.google.android.gms.analytics.CampaignTrackingReceiver" android:exported="true">
      <intent-filter>
        <action android:name="com.android.vending.INSTALL_REFERRER" />
      </intent-filter>
    </receiver>
    <activity android:name="com.unity3d.player.UnityPlayerActivity" android:label="@string/app_name" android:hardwareAccelerated="true">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
    </activity>
  </application>
        
</manifest>

**Comment by yasirkula** [comment]
Your AndroidManifest ends with a `</manifest>`, right? Are you using Gradle build system, and maybe exporting your project to Android Studio? Does PROJECT_Path/Temp/StagingArea/AndroidManifest.xml contain the `<provider ... />` after you build your project to Android?
