### ISSUE TITLE
Fuzzy front camera when recording on iOS

### ISSUE THREAD

**Issue by Akash-PlayPowerLabs** [yasirkula/UnityNativeCamera#121]
When opening the front camera for recording in iOS (both iPhone & iPad), the screen looks fuzzy. 

Here is my code,

`          // Start the recording
            NativeCamera.Permission permission = NativeCamera.RecordVideo((string path) =>
            {
                // Debug.Log($"*** => {path}");
                _videoPath = path;
            }, NativeCamera.Quality.High, 120, 0, NativeCamera.PreferredCamera.Front);
`

Plugins: 1.4.4
Unity version: 2021.3.16f1

**Comment by yasirkula** [comment]
Does omitting this part make any difference: `NativeCamera.Quality.High, 120, 0, NativeCamera.PreferredCamera.Front`

And can you share screenshots from NativeCamera and device's own camera?

**Comment by Akash-PlayPowerLabs** [comment]
It was a specific issue with my device, but it's now working fine. 

However, I've encountered a new problem. I recorded a 30-second video, but there's no audio for the first 15 seconds. After 15 seconds, the audio is very faint. When I use AirPods, I can hear the audio from the beginning, but without them, the audio for the first few seconds is always missing.

**Comment by yasirkula** [comment]
Since AirPods works fine, the recorded video file should be fine. Otherwise the sound wouldn't play on AirPods either. I have no answer to why this strange phenomenon might be occurring.
