### ISSUE TITLE
Doesn't work on MEIZU M5Note

### ISSUE THREAD

**Issue by byelik** [yasirkula/UnityNativeCamera#14]
Hi.
I've created a new project. Created and configured the AndroidManifest as it described [here:](https://github.com/yasirkula/UnityNativeCamera). Then I ran it on my mobile device,(I use your sample from [here)](https://github.com/yasirkula/UnityNativeCamera), touch the screen and I've got permission - "Denied".
And there is no any question about camera permission...
Could you please help me with it?

**Comment by yasirkula** [comment]
Does the code run correctly on another device or on an emulator? Can I see your AndroidManifest.xml? And where did you put it in your project?

**Comment by byelik** [comment]
[New Unity Project 1.zip](https://github.com/yasirkula/UnityNativeCamera/files/2760660/New.Unity.Project.1.zip)

**Comment by byelik** [comment]
> Does the code run correctly on another device or on an emulator? Can I see your AndroidManifest.xml? And where did you put it in your project?

I've created a small project with it.

**Comment by byelik** [comment]
Actually I made it open camera, but I don't see an image from the camera in the image gallery. And also  I can't to pick any image from the image gallery.

**Comment by byelik** [comment]
Sorry for disturbing. Looks like it works fine. Thanks for the plugin and for your help.
