### ISSUE TITLE
Picture Take: Can't find ContentProvider, camera is inaccessible!

### ISSUE THREAD

**Issue by KeyTry** [yasirkula/UnityNativeCamera#15]
First of all, thank you for the awesome plugins. I've been using the Unity native plugins on my app for Share and Gallery access functionality, and now I've been trying to make it work for the camera. This is one of the best solutions I've found and appreciate the work you've done.

I realize this is an issue others have already brought up, but since I'm using several of your plugins at the same time, I'm raising it here as an issue and hopefully it'll be worth looking at.

Whenever I try to open the camera with `NativeCamera.TakePicture()`, I get the following error:

>  Can't find ContentProvider, camera is inaccessible!

This is what my AndroidManifest.xml looks like:

`
<?xml version="1.0" encoding="utf-8"?>

<manifest
    xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.unity3d.player"
    xmlns:tools="http://schemas.android.com/tools"
    android:installLocation="preferExternal">

    <supports-screens
        android:smallScreens="true"
        android:normalScreens="true"
        android:largeScreens="true"
        android:xlargeScreens="true"
        android:anyDensity="true"/>

    <uses-permission android:name="com.android.vending.BILLING" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" android:required="false" />

    <application
        android:theme="@style/UnityThemeSelector"
        android:icon="@mipmap/app_icon"
        android:label="@string/app_name">

        <activity android:name="com.unity3d.player.UnityPlayerActivity"
                  android:label="@string/app_name">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

            <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
        </activity>

      <provider
      android:name="com.yasirkula.unity.UnitySSContentProvider"
      android:authorities="com.MYCOMPANY.MYAPP" // Authority string
      android:exported="false"
      android:grantUriPermissions="true" />

      <provider
      android:name="com.yasirkula.unity.NativeCameraContentProvider"
      android:authorities="com.MYCOMPANY.MYAPP" // Authority string - Same as last one
      android:exported="false"
      android:grantUriPermissions="true" />

    </application>
</manifest>
`

Thank you for your time and I hope to hear back about this issue.

**Comment by yasirkula** [comment]
Hi! Please try using different strings for the two `authorities` in AndroidManifest.
