### ISSUE TITLE
App freezes when trying to cancel to go back in Android

### ISSUE THREAD

**Issue by bnavyata** [yasirkula/UnityNativeCamera#16]
Android app freezes when recordVideo is called and back button is pressed to cancel this operation. Is there a way to cancel incase one changes their mind after the camera turns on to take photo/video?

**Comment by yasirkula** [comment]
Honestly, it is not supposed to freeze like that, at least not after the commit https://github.com/yasirkula/UnityNativeCamera/commit/aaad038e3ad73ed80b82e0de479e29754376dc3f. Is your plugin up-to-date? If you just downloaded it from Asset Store or imported from GitHub, then it should be up-to-date. If your plugin is up-to-date, are there any error messages in logcat that might help me pinpoint the issue?

**Comment by bnavyata** [comment]
I am using the latest version. When calling recordVideo and pressing the back button, the path for the video is null. It throws an ArgumentNullException: Argument cannot be null. How is the plugin expected to behave when the user decides to go back without recording the video/taking the photo? Or is the user expected to finish a recording once the call has been made?

**Comment by yasirkula** [comment]
Plugin returns null if something goes wrong or if the operation is canceled. So, an ArgumentNullException is expected here. Before using the path, you should first check if it is null via string.IsNullOrEmpty and if it is, don't proceed any further.
