### ISSUE TITLE
Taking pictures doesn't work on Moto G6 Plus

### ISSUE THREAD

**Issue by LucasWalters** [yasirkula/UnityNativeCamera#17]
When taking a picture on the Moto G6 Plus device it will correctly show the camera screen but the resulting picture does not exist. It will print out the following error message:

> 04-12 15:48:04.057: E/Unity(17112): UnityException: Internal_CreateGameObject can only be called from the main thread.
> 04-12 15:48:04.057: E/Unity(17112): Constructors and field initializers will be executed from the loading thread when loading a scene.
> 04-12 15:48:04.057: E/Unity(17112): Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
> 04-12 15:48:04.057: E/Unity(17112):   at UnityEngine.GameObject..ctor (System.String name) [0x00000] in <filename unknown>:0 
> 04-12 15:48:04.057: E/Unity(17112):   at NativeCameraNamespace.NCCameraCallbackAndroid.OnMediaReceived (System.String path) [0x00006] in ~\Assets\Plugins\NativeCamera\Android\NCCameraCallbackAndroid.cs:18 
> 04-12 15:48:04.057: E/Unity(17112):   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000c0] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222 
> 04-12 15:48:04.057: E/Unity(17112): Rethrow as TargetInvocationException: NativeCameraNamespace.NCCameraCallbackAndroid.OnMediaReceived(System.String)
> 04-12 15:48:04.065: I/Unity(17112): onResume
> 04-12 15:48:04.098: D/Unity(17112): SetWindow 0 0xce474808
> 04-12 15:48:04.098: D/Unity(17112): SetWindow 0 0xce474808
> 04-12 15:48:04.099: I/Unity(17112): windowFocusChanged: true
> 04-12 15:48:04.099: D/Unity(17112): [EGL] Attaching window :0xce474808
> 04-12 15:48:04.113: D/Unity(17112): ANativeWindow: (1080/2160) RequestedResolution: (0/0) RenderingResolution: (0/0) EGLSurface: (1080/2160)
> 04-12 15:48:04.144: D/Unity(17112): Sensor :        Accelerometer ( 1) ; 0.002396 / 0.00s ; BMI160 Accelerometer / BOSCH 
> 04-12 15:48:04.168: D/Unity(17112): Choreographer available: Enabling VSYNC timing
> 04-12 15:48:05.588: I/Unity(17112): onPause
> 04-12 15:48:05.633: D/Unity(17112): Sensor :        Accelerometer ( 1) ; 0.002396 / 0.00s ; BMI160 Accelerometer / BOSCH 
> 04-12 15:48:05.652: I/Unity(17112): windowFocusChanged: false
> 04-12 15:48:06.411: D/Unity(17112): SetWindow 0 0x0
> 04-12 15:48:06.411: D/Unity(17112): [ 04-12 15:48:06.449  1162:21646 D/         ]
> 04-12 15:48:06.411: D/Unity(17112): <DEBUG> SLSI_PDAF_API: 497: int pd_detection_slsi_parsing_cal_data(st_pd_detection_cal_data_t *), orientation:3
> 04-12 15:48:06.411: D/Unity(17112): [ 04-12 15:48:06.449  1162:21646 D/         ]
> 04-12 15:48:06.411: D/Unity(17112): <DEBUG> SLSI_PDAF_API: 547: PD Detection Init latency:48
> 04-12 15:48:18.455: E/Unity(17112): UnityException: Internal_CreateGameObject can only be called from the main thread.
> 04-12 15:48:18.455: E/Unity(17112): Constructors and field initializers will be executed from the loading thread when loading a scene.
> 04-12 15:48:18.455: E/Unity(17112): Don't use this function in the constructor or field initializers, instead move initialization code to the Awake or Start function.
> 04-12 15:48:18.455: E/Unity(17112):   at UnityEngine.GameObject..ctor (System.String name) [0x00000] in <filename unknown>:0 
> 04-12 15:48:18.455: E/Unity(17112):   at NativeCameraNamespace.NCCameraCallbackAndroid.OnMediaReceived (System.String path) [0x00006] in ~\Assets\Plugins\NativeCamera\Android\NCCameraCallbackAndroid.cs:18 
> 04-12 15:48:18.455: E/Unity(17112):   at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x000c0] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222 
> 04-12 15:48:18.455: E/Unity(17112): Rethrow as TargetInvocationException: NativeCameraNamespace.NCCameraCallbackAndroid.OnMediaReceived(System.String)
> 04-12 15:48:18.463: I/Unity(17112): onResume
> 04-12 15:48:18.491: D/Unity(17112): SetWindow 0 0xce475008
> 04-12 15:48:18.491: I/Unity(17112): windowFocusChanged: true
> 04-12 15:48:18.492: D/Unity(17112): SetWindow 0 0xce475008
> 04-12 15:48:18.492: D/Unity(17112): [EGL] Attaching window :0xce475008
> 04-12 15:48:18.501: D/Unity(17112): ANativeWindow: (1080/2160) RequestedResolution: (0/0) RenderingResolution: (0/0) EGLSurface: (1080/2160)
> 04-12 15:48:18.501: D/Unity(17112): [ 04-12 15:48:18.501  1162:21646 D/         ]
> 04-12 15:48:18.501: D/Unity(17112): <DEBUG> SLSI_PDAF_CAMIF: 596: destroy PD_Detection inst..:0x0
> 04-12 15:48:18.501: D/Unity(17112): [ 04-12 15:48:18.501  1162:21646 D/         ]
> 04-12 15:48:18.501: D/Unity(17112): <DEBUG> SLSI_PDAF_CAMIF: 344: PDAF_CAMIF_deinit(0xf4731770, 0xf4731770)
> 04-12 15:48:18.501: D/Unity(17112): [ 04-12 15:48:18.501  1162:21646 D/         ]
> 04-12 15:48:18.501: D/Unity(17112): <DEBUG> SLSI_PDAF_CAMIF: 194: free 1 pos buf(addr:0xe2a00000)...
> 04-12 15:48:18.501: D/Unity(17112): [ 04-12 15:48:18.501  1162:21646 D/         ]
> 04-12 15:48:18.501: D/Unity(17112): <DEBUG> SLSI_PDAF_CAMIF: 194: free 2 pos buf(addr:0xdca80000)...
> 04-12 15:48:18.501: D/Unity(17112): [ 04-12 15:48:18.501  1162:21646 D/         ]
> 04-12 15:48:18.501: D/Unity(17112): <DEBUG> SLSI_PDAF_CAMIF: 521: destroy PDCAMIF inst..:0x0
> 04-12 15:48:18.539: D/Unity(17112): Sensor :        Accelerometer ( 1) ; 0.002396 / 0.00s ; BMI160 Accelerometer / BOSCH 
> 04-12 15:48:18.560: D/Unity(17112): Choreographer available: Enabling VSYNC timing
> 04-12 15:48:43.105: I/Unity(17112): onPause
> 04-12 15:48:43.170: D/Unity(17112): Sensor :        Accelerometer ( 1) ; 0.002396 / 0.00s ; BMI160 Accelerometer / BOSCH 
> 04-12 15:48:43.190: D/Unity(17112): SetWindow 0 0x0

**Comment by yasirkula** [comment]
Your plugin may not be up-to-date. Please update it from the Asset Store or via this unitypackage: https://github.com/yasirkula/UnityNativeCamera/blob/master/NativeCamera.unitypackage

**Comment by LucasWalters** [comment]
Yup that was it, thanks!
