### ISSUE TITLE
Live Photo .mov option on iOS for select video? 

### ISSUE THREAD

**Issue by yosun** [yasirkula/UnityNativeCamera#18]
Does such an option exist? 

Live Photo .mov option on iOS for select video?

**Comment by yasirkula** [comment]
I think it should be possible with a little modification. I can't work on it right now but please google "uiimagepickercontroller record live photo" to see how it can be achieved.

**Comment by yasirkula** [comment]
I've decided not to implement this feature since it is not multi-platform and IMO there is not much use-case for it.
