### ISSUE TITLE
Can't preview video taken on Android

### ISSUE THREAD

**Issue by morettyCat** [yasirkula/UnityNativeCamera#19]
Hi!

First of all thanks for your extraordinary work!

In my app, you can record a video to participate into a contest. Everything works well on iOS, and 90% works well on Android. Let me explain it step by step:

· You push a button to record, native camera jumps perfect.
· You record your video and stop when you're ready.
· You return to unity and some things happen:
      1. Your video url get's setted on a videoPlayer.
      2. A "PLAY" button is shown over videoPlayer.
      3. A button is activated so you can participate to contest.

For some strange reason, in Android devices, the video gets only in "black" color, but audio works fine, when the video reaches the play button gets alive again so everything seems to work fine inside unity, except the "video" that is playing in black (but with audio OK).

The most strange thing is that when you upload your participation, the video downloaded by the "participation gallery" can be played without problems.

Is there anything in NativeCamera that I am not doing well?
Is the url passed by NativeCamera fully accessible for OS?
Is there any "codec" parameter I am omitting?

Or maybe is it a bug on Android&VideoPlayer? But in fact the most strange thing is that the SAME video is playing when it comes from the uploaded version but don't when it comes from the camera URL.

Thanks in advance!

**Comment by yasirkula** [comment]
I believe it is a VideoPlayer issue but you can try copying/moving the recorded video to some other path (like Application.persistentDataPath) to see if it changes anything.

**Comment by morettyCat** [comment]
Ok, i'll try and will share here the experience. Thanks for your quick reply!
