### ISSUE TITLE
 crashed in ios and hang in android

### ISSUE THREAD

**Issue by parth521** [yasirkula/UnityNativeCamera#2]
video recording when call record video fuction it's crashed in ios.
video recording when call record video fuction application hand on android.

**Comment by yasirkula** [comment]
Does it give any error messages on these platforms? What are your device specs?

**Comment by parth521** [comment]
i check in iphone 6s.
for android  i checked in multiple device like one plus one,mi note 3.

not tried for image capture thing cause currently only i need is record a video.
and  i want to know you that i also integrate your gallery plugin and that works fine.

**Comment by parth521** [comment]
Above issue solved just need to add permission for microphone in info.plist. 
and in android i just move all the data from multiple android folder to one and issue solved.

**Comment by yasirkula** [comment]
I didn't know that a microphone description was necessary, thanks! I didn't have that issue myself while testing but probably microphone description was already set to a predefined value in my case.

Android solution was unexpected for me, though. I'll try to replicate the issue. Are you calling SaveToGallery immediately after recording a video?

**Comment by fabiotgolo** [comment]
Hi!
Do you have some video tutorial showing how to set up this plugin?
I'm asking because I don't know how to config the button to record the video and stop recording.

**Comment by yasirkula** [comment]
No manual setup is required. You can use the example code as a head start: https://github.com/yasirkula/UnityNativeCamera#example-code
