### ISSUE TITLE
Question: Picture size

### ISSUE THREAD

**Issue by Siccity** [yasirkula/UnityNativeCamera#20]
Hello, just trying out this plugin for the first time and I have a few questions.

* Does `maxSize` refer to the horizontal or vertical size of the picture?
* You state that `maxSize` does not work for Android. How do you suggest we change the size of a picture taken with Android?

**Comment by yasirkula** [comment]
- Both. Whichever is the largest (and is bigger than maxSize), it will be scaled down to maxSize
- You can google "unity scale texture". You can also see [TextureOps.Scale](https://github.com/yasirkula/UnityTextureOps#b-texture-operations) for example implementation

**Comment by Siccity** [comment]
So, take the photo, load it from path, scale it, then save back to path?

**Comment by yasirkula** [comment]
I actually forgot the LoadImageAtPath function. If you are only interested in the size of the Texture that is generated from the image, then you can use LoadImageAtPath with a specified maxSize. It works on both platforms and should be quite fast.

If you really need to scale the source image file, then the workflow you've summarized is the way to go on Android.

**Comment by Siccity** [comment]
Alright thanks :)
