### ISSUE TITLE
Vertical screen recording does not get normal images

### ISSUE THREAD

**Issue by ShenKang4181** [yasirkula/UnityNativeCamera#22]
I have a very annoying bug, which is to record video. There is no problem with the horizontal screen recording of the mobile phone. The vertical screen will display the color blocks.

**Comment by yasirkula** [comment]
Can you share a screenshot of the issue?

**Comment by ShenKang4181** [comment]
This is the problem video I shot.
[http://cun.huimeiwed.com/a.mp4](url)
[http://cun.huimeiwed.com/b.mp4](url)

**Comment by yasirkula** [comment]
Please don't get me wrong but I'd prefer not to click on those links because the domain huimeiwed.com sounds a little suspicious. How about taking a screenshot of the issue and attaching it here or uploading the video to some other popular video sharing platform?

**Comment by ShenKang4181** [comment]
Ok, I won't send images or videos via git (nowhere I found them), and I won't be able to manipulate some video sharing URLs, but I will upload them to my company's server, but that's okay, I have solved this problem. My unity version is 2017.3.1f1, this videoplayer component may not be mature (does not support some kind of thing), probably I can't say anything, I used the avproplayer component to play, it solved my problem, but ,Thank you!  (๑•ㅂ•́)و✧

**Comment by yasirkula** [comment]
Glad the issue is resolved!
