### ISSUE TITLE
Any way to disable "retry" screen after taking the photo and go straight back to unity?

### ISSUE THREAD

**Issue by dani-inr** [yasirkula/UnityNativeCamera#23]
Hi there! Before anything else, great plugin and thanks for sharing!

Is there any way to disable the "retry" screen that shows up after taking the photo and go straight back to unity?

**Comment by yasirkula** [comment]
It doesn't seem possible. Please see:

- https://stackoverflow.com/questions/35956635/android-take-camera-picture-intent-remove-confirmation-dialog
- https://stackoverflow.com/questions/38581244/how-to-skip-or-avoid-retake-and-review-option-after-captureing-photo-from-came

The suggested SurfaceView option is unfortunately not an option for this plugin.

**Comment by dani-inr** [comment]
Ah! I see, so is part of the native camera app... then it makes totally sense to not touch it ;). I was thinking that it was a native activity created from the plugin native side to confirm the image.

All good then, thanks a lot for the info and the super quick reply!

**Comment by yasirkula** [comment]
You are welcome, thanks for choosing UnityNativeCamera!
