### ISSUE TITLE
Capturing Augmented Reality content

### ISSUE THREAD

**Issue by knightcube** [yasirkula/UnityNativeCamera#25]
I have an AR camera in my scene and I want to capture the view of that camera rather than launching the phone's internal camera all the time. Currently the problem is that when I augment any game object on a marker I want to capture the view right then only because the AR camera is also accessing the device's camera. So if I press on the capture button it is opening the device's camera that does not have augmented content.

Is there a way to take the camera in the scene and capture the image or record from that camera?

**Comment by yasirkula** [comment]
Screen recording is not supported. I think the best free solution for this is [Everyplay](https://github.com/Everyplay/everyplay-unity-sdk); although it is no longer being developed, it should still be stable. Alternatively, the most popular paid solution, AFAIK, is [NatCorder](https://forum.unity.com/threads/natcorder-video-recording-api.505146/).

**Comment by knightcube** [comment]
Natcorder has issues with Wikitude - https://forum.unity.com/threads/natcorder-video-recording-api.505146/page-40

**Comment by yasirkula** [comment]
I haven't used NatCorder myself. I'd recommend you to give Everyplay a shot, since it records the screen, not the output of a game camera.
