### ISSUE TITLE
How To Get Video Path 

### ISSUE THREAD

**Issue by parth521** [yasirkula/UnityNativeCamera#3]
How to save video to gallery which just recorded. i tried NativeGallery.SaveVideoToGallery function but i did't get video path which just recorded.

**Comment by yasirkula** [comment]
The path is returned inside the CameraCallback function that you pass as parameter to the RecordVideo function (see [Example Code](https://github.com/yasirkula/UnityNativeCamera#example-code)).

If, instead, you are trying to get the path of the video that is just saved to the Gallery, then there is a trick for this but it only works on Android: set the visibility of NativeGallery.GetSavePath function to public and call it before calling SaveVideoToGallery function. The returned path will store the path of the video in Gallery on Android.

**Comment by parth521** [comment]
hello is this possible to record video portrait(Vertical) cause when i am trying play video on unity default video player it's play left or right. i want to play it full screen.  any idea?

**Comment by yasirkula** [comment]
Hmm, I'll see if that is possible. For now, you can try setting Screen.orientation to ScreenOrientation.Portrait before recording the video and then reverting its value back in CameraCallback.

**Comment by parth521** [comment]
is it possible to get video is recorded from rear cam or front cam?

**Comment by parth521** [comment]
so problem with video player not with recording ? so can you give me any solution that.

**Comment by yasirkula** [comment]
I've added `NativeCamera.GetVideoProperties` function with the latest update. You can rotate your video player by *rotation* degrees (clockwise) to display the video correctly.

**Comment by parth521** [comment]
thanks for support it's done.
