### ISSUE TITLE
Removing automatic camera permission request at start

### ISSUE THREAD

**Issue by bitCoder0** [yasirkula/UnityNativeCamera#30]
hey
how to remove auto permission request at the start?
some users deny that because of security risk
any idea?
thanks

**Comment by yasirkula** [comment]
You can add the following line inside the `<application>...</application>` tag of _Plugins/Android/AndroidManifest.xml_:

`<meta-data android:name="unityplayer.SkipPermissionsDialog" android:value="true" />`

If your project doesn't have an AndroidManifest, you can copy Unity's default one from _C:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer_ (it might be located in a subfolder, like '_Apk_') to _Assets/Plugins/Android_.

**Comment by bitCoder0** [comment]
Alright thanks
