### ISSUE TITLE
using native camera with AR Foundation

### ISSUE THREAD

**Issue by shacharoz** [yasirkula/UnityNativeCamera#31]
do you have an idea how should i use native camera together with a device camera that is already open and being used (such as AR cases)? 

to be specific i am using AR Foundation  with unity.
when i try to use a simple rendertexture it doesnt work

**Comment by shacharoz** [comment]
i just realized that native camera opens the actual camera app.
i need to take a screenshot from a unity app that already have the camera open.
i assume i am supposed to be using NativeGallery instead. 
is that correct?

**Comment by yasirkula** [comment]
You don't need a plugin for capturing a screenshot. NativeGallery is useful if you are planning to save the screenshot to Gallery, otherwise you may consider using [ScreenCapture.CaptureScreenshot](https://docs.unity3d.com/ScriptReference/ScreenCapture.CaptureScreenshot.html).

**Comment by shacharoz** [comment]
all solved with nativegallery.
i will publish a sample project soon
