### ISSUE TITLE
Android front camera unable to record video

### ISSUE THREAD

**Issue by ksyao2002** [yasirkula/UnityNativeCamera#35]
I am testing my build on a Oneplus 7 pro and I am having issues with recording videos using the front camera. Whenever I press the record button it disappears and then I am unable to stop the video until it gives me the message "Recording Stopped Due to Error." I don't have the same issue with the rear camera: it can record videos perfectly fine. I read from the other issues (https://github.com/yasirkula/UnityNativeCamera/issues/26) that it may depend on the android phone being used. My question is: is there any way to modify the plugin code to address this? Also, I wanted to get a general idea of what android phones would have such an issue, so maybe if the majority of phones don't get this problem then it is still usable in my project.

**Comment by yasirkula** [comment]
Actually, if there are multiple camera apps installed, the plugin [should](https://github.com/yasirkula/UnityNativeCamera/blob/1d6c5afa7fa1762027f7c286a7fa1ecfd3c2fd66/.github/AAR%20Source%20(Android)/NativeCameraVideoFragment.java#L137-L138) prompt the user to pick one of them.

NativeCamera isn't a camera app itself, it can only launch existing camera apps on the device. If the same camera app isn't installed on all Android devices, NativeCamera can't do anything about it.

**Comment by ksyao2002** [comment]
Awesome, thanks for your response! I downloaded the GCam mod (google pixel camera) on my OnePlus (using this tutorial: https://www.theandroidsoul.com/how-to-download-oneplus-7-pro-gcam-apk-port-google-cam-camera/) and set it as the default camera app, and now there are no issues. It seems to just be a problem with the OnePlus camera software.
