### ISSUE TITLE
NativeCamera.RequestPermission() requests Camera and then Storage

### ISSUE THREAD

**Issue by andrewio** [yasirkula/UnityNativeCamera#36]
So I have 2 request windows in sequence on Android 10 if I call NativeCamera.RequestPermission(). I need only Camera Permission Window. 

What is the result of this operation? 
It combines answers of 2 windows like && operator?

Or if the result is only related to Camera then How can I get the result of Storage in Code separately?

**Comment by yasirkula** [comment]
The result is combined like && operator, yes. NativeCamera doesn't have an interface to ask only a single permission, you'd have to use another asset for it (like [this](https://github.com/yasirkula/UnityAndroidRuntimePermissions)).

**Comment by andrewio** [comment]
> The result is combined like && operator, yes. NativeCamera doesn't have an interface to ask only a single permission, you'd have to use another asset for it (like [this](https://github.com/yasirkula/UnityAndroidRuntimePermissions)).

There is a strange behavior in way that after NativeCamera.RequestPermission() on Android 10, I have some OnApplicationFocus(true) calls in sequence. So If I tap "Allow" on 2 windows then 2 calls.

**Comment by yasirkula** [comment]
I'm open to suggestions for fixing this issue.

**Comment by andrewio** [comment]
> I'm open to suggestions for fixing this issue.

I don't know how native code behaves, but in Unity we can return to app flow and skip the frame if we call "yield return null;" inside coroutine. I don't know how it can help you, just an idea.

P.S. My example is not related with coroutines.

**Comment by yasirkula** [comment]
I ask Android OS to request both Camera and Storage permissions in a single call and it decides to request these permissions one after another. If these 2 permission prompts trigger OnApplicationFocus separately, I don't really think that this issue can be avoided.

**Comment by andrewio** [comment]
> I ask Android OS to request both Camera and Storage permissions in a single call and it decides to request these permissions one after another. If these 2 permission prompts trigger OnApplicationFocus separately, I don't really think that this issue can be avoided.

So would be ok if there were 2 separate OnApplicationFocus calls, but it's not. 
There are 2 calls in one time (after 2 windows were showed and answered). 

Just for clarifying.

**Comment by yasirkula** [comment]
Do you want at least 1 frame delay between these 2 calls?

**Comment by andrewio** [comment]
> Do you want at least 1 frame delay between these 2 calls?

It would be just more logical, I guess. To avoid 2 OnApplicationFocus calls in one time.

**Comment by yasirkula** [comment]
On a second thought, probably these two function calls are like this:

1. OnApplicationFocus(false)
2. OnApplicationFocus(true)

To fetch the permission result immediately, Unity's main thread is frozen until the permission dialog is closed. That's probably why these 2 calls are sequential. You'll need to ask these permissions asynchronously.

NativeGallery doesn't support it since most users would prefer to receive the permission result immediately instead of having to use a callback. You should use either Unity's [Permission](https://docs.unity3d.com/Manual/android-RequestingPermissions.html) system or a plugin that asks permissions without blocking the main thread. In the permission callback, only if the permissions are granted should you call NativeCamera's functions.

**Comment by andrewio** [comment]
> On a second thought, probably these two function calls are like this:
> 
> 1. OnApplicationFocus(false)
> 2. OnApplicationFocus(true)
> 
> To fetch the permission result immediately, Unity's main thread is frozen until the permission dialog is closed. That's probably why these 2 calls are sequential. You'll need to ask these permissions asynchronously.
> 
> NativeGallery doesn't support it since most users would prefer to receive the permission result immediately instead of having to use a callback. You should use either Unity's [Permission](https://docs.unity3d.com/Manual/android-RequestingPermissions.html) system or a plugin that asks permissions without blocking the main thread. In the permission callback, only if the permissions are granted should you call NativeCamera's functions.

I get 2 OnApplicationFocus(true)

**Comment by yasirkula** [comment]
I can't put a delay between the 2 permission prompts, otherwise the permission system will have to be asynchronous. My previous suggestion should still be valid.
