### ISSUE TITLE
Requirement for skip the "save"/"delete" cofirm page

### ISSUE THREAD

**Issue by renyunhao** [yasirkula/UnityNativeCamera#37]
First, I have to say, this is a awsome plugin which make call to native camera so easy.
But on Android device, after I take photo, a confirm page show, I have to press "save" or "delete"。
Could you please add a option to skip this page?
I searched on google, then get this information:
add `intent.putExtra("android.intent.extra.quickCapture",true);` to the camera intent can skip the confirm page, hope this can do some help。
I want to take photo continuesly without confirm and open again, is that possible?
Best regards

**Comment by yasirkula** [comment]
This will probably work on a fraction of Android devices but it wouldn't hurt to add it. I will add it in a following update.

**Comment by renyunhao** [comment]
Oh, I am so happy to hear this. Thank you so much.
I read the google source code: https://android.googlesource.com/platform/packages/apps/LegacyCamera/+/refs/heads/master/src/com/android/camera/Camera.java#205

**Comment by yasirkula** [comment]
Can you replace Plugins/NativeCamera/Android/NativeCamera.aar with the one inside the attached zip archive and see if it works?
[NativeCamera.zip](https://github.com/yasirkula/UnityNativeCamera/files/4798832/NativeCamera.zip)

**Comment by renyunhao** [comment]
It works! Thank you for your quickly awsome work.
Check this gif.
![QuickCapture](https://user-images.githubusercontent.com/8768880/85094603-bf37ee00-b221-11ea-99fe-83dd4c3760d9.gif)

**Comment by yasirkula** [comment]
It didn't have any effect on my S8's default camera app but I'm happy to hear that the solutions works on your device :)

**Comment by renyunhao** [comment]
Haha, as I searched, samsung device and huawei device has no effect. Maybe because these two always like to modify android source code.
