### ISSUE TITLE
Is it possible to take multiple different pictures using TakePicture and save them in the Gallery?

### ISSUE THREAD

**Issue by SIlvaMFPedro** [yasirkula/UnityNativeCamera#39]
Good morning.
I have been using your plugin but i can't seem to be able to record 10 different pictures and save them in the Gallery.
Here is my code:
![image](https://user-images.githubusercontent.com/22821533/87539330-9c202300-c695-11ea-9fe1-b7e34b9f8582.png)
![image](https://user-images.githubusercontent.com/22821533/87539464-d689c000-c695-11ea-88f2-090c96751e20.png)
With this code i can record 10 images and save them in a .jpg file but at the end all the files show the last image that i recorded from my phone which it is not what i wanted (what i want is a sequence of images not the last one replicated).
Can anyone help me with this please? ( i am rather new to Unity and Android)
Is there a TakeMultiplePictures method?

Thanks!

**Comment by yasirkula** [comment]
I'd recommend you to change your code as follows:

```csharp
while(imageCounter < 10)
{
	yield return StartCoroutine(TakePicture(512));
	imageCounter++;
}
```

```csharp
private IEnumerator TakePicture(int maxSize)
{
	bool tookPicture = false;
	
	NativeCamera.Permission permission = NativeCamera.TakePicture((path) =>
	{
		tookPicture = true;
		
		// Rest of TakePicture
	}, maxSize);
	
	while(!tookPicture)
		yield return null;
}
```

This way, you actually wait for the previous TakePicture call to finish before invoking TakePicture again.

**Comment by SIlvaMFPedro** [comment]
That solved my issue. Thank you very much ;)
