### ISSUE TITLE
Recording in the background

### ISSUE THREAD

**Issue by Rich2020** [yasirkula/UnityNativeCamera#41]
Great plugin - just tested and it worked 1st time without issue.

I am developing an Augmented Reality app and I need to capture _raw_ video content (i.e. not the screen - I don't want any overlays visible).  Ideally, the recording will happen in the background so that I do not need to click buttons... but I can simulate the press with ADB if it's not possible.

I also **DO NOT** want the preview. There is apparently some trick where you can set the preview to be 1px by 1px (so that it is not visible).

Is it possible to do this with UnityNativeCamera and if yes, how?

Thanks!

**Comment by yasirkula** [comment]
This requires accessing the camera feed (and possibly passing it to a Texture) but NativeCamera doesn't support it. You probably need a solution like NatCam: https://assetstore.unity.com/packages/tools/integration/natdevice-media-device-api-162053

**Comment by Rich2020** [comment]
Great, thanks for your response. Much appreciated!
