### ISSUE TITLE
Not permitted to use Camera even though I accept the permission dialog.

### ISSUE THREAD

**Issue by DrOffensive** [yasirkula/UnityNativeCamera#46]
**Description of the bug**
When trying to call TakePhoto i get the permission dialogs that I can accept. But even after I accept them the camera tells me that I didn't have permission to open it.
I get no errors in the LogCat apart from the permission log a make after the calling the camera
"Camera permission: Denied"

**Reproduction steps**
Call TakePhoto() on a android device. Accept the permission dialogs. Nothing happens.

**Platform specs**
Android 10
- Unity version: 2019.4f9
- Platform: Windows, Android
- Device: All tested Android devices
- How did you download the plugin: Asset Store

**Comment by DrOffensive** [comment]
Sorry, it seems the issue was related to some project settings.
Using the plugin in an empty project works fine.

**Comment by yasirkula** [comment]
I'm happy to hear that but also puzzled at the same time. Perhaps the fix with `tools:node="replace"` in [this FAQ](https://github.com/yasirkula/UnityNativeGallery/#faq) also applies to NativeCamera? Please let me know if you manage to find a solution.

**Comment by DrOffensive** [comment]
Thank you so much!
I've been struggling with this for days.
The fix in the FAQ did the trick.

Den man. 14. sep. 2020 kl. 16.33 skrev Süleyman Yasir KULA <
notifications@github.com>:

**Comment by yasirkula** [comment]
Glad the issue is resolved :)
