### ISSUE TITLE
How to change message text in permission window on iOS?

### ISSUE THREAD

**Issue by andrewio** [yasirkula/UnityNativeCamera#47]

**Comment by yasirkula** [comment]
You can change them from here (note that I've also updated those texts recently): https://github.com/yasirkula/UnityNativeCamera/blob/9b86397e0239502e72bd9246a96e2f3e917fd219/Plugins/NativeCamera/Editor/NCPostProcessBuild.cs#L13-L14

**Comment by andrewio** [comment]
Add it to FAQ.
And as Idea, You can add fetching from appropriate fields of Project Settings (iOS)

**Comment by yasirkula** [comment]
It is in the [iOS Setup section](https://github.com/yasirkula/UnityNativeCamera#ios-setup). Second idea has pros (the field inside Player Settings is used) but also cons (requires manual input from developer which must also be mentioned in iOS Setup section). So I don't want to change this behaviour.
