### ISSUE TITLE
does that include the canvas components?

### ISSUE THREAD

**Issue by midopooler** [yasirkula/UnityNativeCamera#48]
Hello again,  @yasirkula . I want to know before using this, Does this capture canvas components on the screen as well or not? 
If no, how I can make it exclude them?

I have previously used some other screen recorder but capturing/not capturing the canvas was not much concern there, But this time I have to exclude all the canvas part and take only the AR content just like Snapchat do.

**Comment by yasirkula** [comment]
This plugin doesn't record the screen. It launches device's native camera app, prompts it to record a video, waits for the camera app to finish recording and finally, forwards the recorded video's path to Unity.

**Comment by midopooler** [comment]
Thanks for the clarification. I'm closing this issue.
