### ISSUE TITLE
adding load photo from gallery from the native camera screen

### ISSUE THREAD

**Issue by shacharoz** [yasirkula/UnityNativeCamera#49]
is there any way that we can have a button to add picture from the gallery from the native camera screen?

this is a feature request and not a bug.

**Comment by yasirkula** [comment]
I don't have any control over the native user interface, so you must create a UI with 2 buttons in Unity and use either NativeGallery or NativeCamera depending on the pressed button.

**Comment by shacharoz** [comment]
ok. yes.
that was my backup plan...
