### ISSUE TITLE
Where is actual native code?

### ISSUE THREAD

**Issue by ffriande** [yasirkula/UnityNativeCamera#53]
Hi, 
If this is a plugin that accesses native android/iOS cameras, shouldn't there be native mobile code somewhere? 
Where is the actual Java/Kotlin and Objective-C/Swift code to access the camera and then call it with your plugin?
Sorry if I'm being ignorant, but I'm very interested in changing some stuff in the native code.
Thanks in advance

**Comment by yasirkula** [comment]
There you go: https://github.com/yasirkula/UnityNativeCamera/tree/master/.github/AAR%20Source%20(Android). It is compiled into NativeCamera.aar in Android Studio. NativeCamera.cs communicates with the native source code using Unity's AndroidJavaObject, AndroidJavaClass and AndroidJavaProxy classes.

**Comment by ffriande** [comment]
Thanks, I hadn't seen these files. I still can't see where the iOS code is...

**Comment by ffriande** [comment]
Thanks a lot! How could I make changes in this code and then compile it again in .aar ?

**Comment by yasirkula** [comment]
You need to google "unity android studio native plugin".
