### ISSUE TITLE
Taking multiple shots on iOS14.4 can crash the game

### ISSUE THREAD

**Issue by TastSong** [yasirkula/UnityNativeCamera#56]
![image](https://user-images.githubusercontent.com/32432306/110298585-b5fce480-802f-11eb-887a-a2618829d055.png)
![image](https://user-images.githubusercontent.com/32432306/110298633-c57c2d80-802f-11eb-9227-1d107733b9b2.png)

The game crashed after repeated shots, and the lower version of iOS didn't crash

**Comment by yasirkula** [comment]
If you aren't destroying the previously captured Texture when it isn't needed, perhaps your game runs out of memory? Try destroying previous Textures (if any) after a new photo is taken and don't forget to set a sufficiently low maxSize parameter.

**Comment by TastSong** [comment]
thanks
