### ISSUE TITLE
is it possible to start the camera in full screen already?

### ISSUE THREAD

**Issue by shacharoz** [yasirkula/UnityNativeCamera#57]
normally, when you start the camera first time, it starts on a 4:3.
once you change that mode (i.e. full screen or 16:9), then it stays on that mode for future times.
i would like to start the camera at full screen the first time.

**Platform specs**
- Unity version: 2019 LTS
- Platform: Android, iOS
- Device: Samsung Galaxy S20, Android 10*
- How did you download the plugin: Asset Store

**Comment by yasirkula** [comment]
I don't think there is a parameter for that. Unfortunately, there are only few programmable customization options for native camera apps and this doesn't seem to be one of them: https://stackoverflow.com/questions/46972922/open-camera-with-picture-size-as-169-programatically
