### ISSUE TITLE
Request Take Selfie

### ISSUE THREAD

**Issue by gw1108** [yasirkula/UnityNativeCamera#6]
Is it possible to use TakePicture and go straight into selfie mode? When I call TakePicture on iOS it seems to default to taking pictures instead of taking selfies.

**Comment by yasirkula** [comment]
On iOS, you can try adding `imagePicker.cameraDevice = UIImagePickerControllerCameraDeviceFront;` [here](https://github.com/yasirkula/UnityNativeCamera/blob/dcaf893b59658cba669d36b419bc558ba94f094d/Plugins/NativeCamera/iOS/NativeCamera.mm#L123) ([credit](https://stackoverflow.com/a/8950105/2373034)).

**Comment by RenegadeHawk** [comment]
Is there a way to launch selfie by default in android ?

**Comment by yasirkula** [comment]
AFAIK, it is not possible. There is something called `android.intent.extras.CAMERA_FACING` but it is said to be not working on a large number of devices (maybe the majority of the devices).

**Comment by yasirkula** [comment]
Added PreferredCamera parameter in https://github.com/yasirkula/UnityNativeCamera/commit/a070c0a0b7648116e69e3723a500b674665ce6a2
