### ISSUE TITLE
Request Permission does not showing up

### ISSUE THREAD

**Issue by nintendaii** [yasirkula/UnityNativeCamera#62]
**Description of the bug**
Hey! I was using your plugin to access the camera in my AR project (unity 2019.3.3f1). I simply called the RequestPermission method and it worked perfect. It opened the dialogue window with permission (see screenshot 1)
![image](https://user-images.githubusercontent.com/44233090/120628538-777b9800-c46d-11eb-89ff-2c24db468245.png)
However, when I tried to create the same project in unity 2021.1.3f1 it started to open the wrong dialogue window so I couldn't access the camera:
![image](https://user-images.githubusercontent.com/44233090/120628733-b3aef880-c46d-11eb-9232-8a8a3fd7a8a1.png)
In both cases I used Samsung M31. The build was made in MacBook Pro 16. I downloaded the plugin via GitHub's unitypackage file.
Here is the code I used in both projects:
```c#
if (NativeCamera.CheckPermission()==NativeCamera.Permission.ShouldAsk || NativeCamera.CheckPermission()==NativeCamera.Permission.Denied)
        {
            NativeCamera.RequestPermission();
        }
```
P.S. Sorry for the Ukrainian language on the screens)

**Comment by yasirkula** [comment]
What does NativeCamera.RequestPermission return? Camera permission is asked only if it is declared in AndroidManifest. Since that permission isn't mandatory, it's OK for it to be not asked. Storage permission is always asked but the camera permission is optional, as I said.

**Comment by nintendaii** [comment]
Thanks for the reply. Ok got it but the weird thing is that I have not modified the AndroidManifest file in any project. But the Camera permission was called in unity 2019.3.3f1 build and was not called in unity 2021.1.3f1 build. So what exactly should I change in my AndroidManifest file?

**Comment by yasirkula** [comment]
Camera permission must have come from the AR plugin on 2019.3. I don't know why the same plugin doesn't add camera permission on 2021.1. Does this affect the camera functionality in any way?

**Comment by nintendaii** [comment]
Idk why the permission is not called by ARFoundation. When I opened my app the screen was black. Then when I added the Camera permission code from your plugin it started to work (2019.3.3f1 build). So I tried to do the same thing with the 2021.1.3f1 version. Anyway, this topic is not about it. I think I should rewrite the AR logic. Thanks.

**Comment by nintendaii** [comment]
Yeah, I fixed the problem. It was the issue with ARFoundation and not with NativeCamera plugin. Sorry for this :) Have a nice day
