### ISSUE TITLE
Xcode error when attempting to build project

### ISSUE THREAD

**Issue by alyazyah** [yasirkula/UnityNativeCamera#63]
My project is successfully running on Unity, but I run into an issue when I try to compile on Xcode. I get the following error:

/Libraries/Plugins/NativeCamera/iOS/NativeCamera.mm:120:25: Incompatible pointer types assigning to 'id<UINavigationControllerDelegate,UIImagePickerControllerDelegate> _Nullable' from 'Class'

<img width="1134" alt="Screen Shot 2021-06-07 at 4 29 38 AM" src="https://user-images.githubusercontent.com/37453063/120945136-fbbd6c00-c748-11eb-9c5d-28fc3a839136.png">

Unity version 2020.1.8f1
iPhone 8+ running iOS 14.4.1, Xcode version 12.5

Is there a way to fix this? Thank you!

**Comment by yasirkula** [comment]
I'd recommend you to delete the plugin completely and reimport the latest version from GitHub or Asset Store. If, for some reason, this is not an option for you, you can change the problematic line to `imagePicker.delegate = (id) self;`.

**Comment by ksyao2002** [comment]
I also had the same error. I reimported the latest version of the asset but still had the same issue. Putting (id) before self fixed the issue

**Comment by yasirkula** [comment]
[There seems to be some sort of Asset Store cache issue when Package Manager is used](https://github.com/yasirkula/UnityNativeGallery/issues/200). I don't know if Unity is aware of that.
