### ISSUE TITLE
Importing unity as a module into native android project

### ISSUE THREAD

**Issue by rulfox** [yasirkula/UnityNativeCamera#64]
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find :NativeCamera:.
     Required by:
         project :app > project :unityLibrary

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by yasirkula** [comment]
Is the issue reproducible in a new Unity project? If so, on which version?

**Comment by rulfox** [comment]
implementation project(':unityLibrary')
implementation fileTree(dir: project(':unityLibrary').getProjectDir().toString() + ('\\libs'), include: ['*.jar'])

The link to files was not defined in the project.
Once it was corrected, the issue was fixed
