### ISSUE TITLE
Picture path sometimes not accessible on Android

### ISSUE THREAD

**Issue by Mythique** [yasirkula/UnityNativeCamera#65]
**Description of the bug**

After calling NativeCamera.TakePicture(), I want to copy the file taken to another location. Sometimes the File.Copy() will result in en error : `ArgumentNullException: Value cannot be null. Parameter name: sourceFileName`

Here is the stack trace :

```
System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <9577ac7a62ef43179789031239ba8798>:0)
System.IO.File.Copy (System.String sourceFileName, System.String destFileName) (at <9577ac7a62ef43179789031239ba8798>:0)
Ohrizon.Socotec.FileManager.CopyImage (System.String path, Ohrizon.Socotec.IPicturesDataVariable picturesData, Ohrizon.Socotec.EIP eip) (at <4d78fa4bc0b441bfba66d59627307cf4>:0)
Ohrizon.Socotec.NativeCameraBehaviour.PictureCallback (System.String path) (at <4d78fa4bc0b441bfba66d59627307cf4>:0)
NativeCameraNamespace.NCCameraCallbackAndroid.MediaReceiveCallback (System.String path) (at <6996d51f3f5e4bb4840bab57a9971e5d>:0)
NativeCameraNamespace.NCCameraCallbackAndroid+<>c__DisplayClass3_0.<OnMediaReceived>b__0 () (at <6996d51f3f5e4bb4840bab57a9971e5d>:0)
NativeCameraNamespace.NCCallbackHelper.Update () (at <6996d51f3f5e4bb4840bab57a9971e5d>:0)
```

And here are the function called :

`NativeCamera.TakePicture(PictureCallback);`

```
private void PictureCallback(string path)
{
    FileManager.CopyImage(path);
}
```
```
public static void CopyImage(string path)
{
    string picturePath = ImportExportFiles.GetPicturePath();
    File.Delete(picturePath);
    File.Copy(path, picturePath);
}
```

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: 2019.4.27f1
- Platform: Android (8, 10, 11)
- Device: Samsung SM-T500
- How did you download the plugin: Package Manager, version 1.2.6

**Comment by yasirkula** [comment]
NativeCamera returns _null_ path when camera is closed without capturing a photo. This looks to be case to me?

**Comment by Mythique** [comment]
> NativeCamera returns _null_ path when camera is closed without capturing a photo. This looks to be case to me?

Looks like this is it... The error was thrown from our user devices, and I could not reproduce the issue when taking a picture. It didn't even crossed my mind to test this. Thanks for your help.
