### ISSUE TITLE
Skip Retake and Use Video

### ISSUE THREAD

**Issue by vinayvidhani** [yasirkula/UnityNativeCamera#66]
Hi, First of all love you man you gave us this plugin free. When I am done with recoding video I am getting one overlay screen with 3 buttons Retake, Play and Use Video respectively. I do not want that. Could you help me out How I can remove this. Please!

**Comment by yasirkula** [comment]
Thank you for your support! About this issue, please see: https://github.com/yasirkula/UnityNativeCamera/issues/23
