### ISSUE TITLE
Video storage location and access

### ISSUE THREAD

**Issue by ksyao2002** [yasirkula/UnityNativeCamera#67]
I am building to iOS, and I was wondering where the video gets stored after the video is taken. I checked photos and files, but did not find the recorded video anywhere. Is it automatically deleted? I know I can use your other plugin, Unity Native Gallery, to save it to the photos, but I was wondering if there was a more direct way to access where all the videos are stored. I am trying to have my custom app show previously recorded videos in the app using this plugin.

Unity Version: 2019.3.12
iOS version: (iPAD)14.6
UnityNativeCamera: v1.2.8

**Comment by yasirkula** [comment]
iOS's video recording API saves the videos to application's local directory, somewhere near Application.dataPath. If you are attempting to find the directory where all videos in Photos app are stored, I don't think you can. I've never heard of such a folder so even if it exists, it is probably a restricted folder.

**Comment by ksyao2002** [comment]
Thanks for the quick response! Does that mean the video gets deleted after a while if it cannot be accessed ever again?

**Comment by yasirkula** [comment]
Unless you move the video to persistentDataPath, you can expect the video to be deleted by the OS when device runs out of free storage.

**Comment by ksyao2002** [comment]
Got it, thanks!
