### ISSUE TITLE
Debug error when i try to builg project

### ISSUE THREAD

**Issue by Akira8707** [yasirkula/UnityNativeCamera#68]
My project is successfully running on Unity,And i also build a android apk,it runs good.  but i get lot's of errors when I try to compile on Xcode. I have followed the Setup:

<img width="643" alt="{CC2F2907-D20C-BE95-9095-46E97FF744CB}" src="https://user-images.githubusercontent.com/85773014/121761732-15551e00-cb64-11eb-9962-402f3002d2bd.png">
<img width="689" alt="{41196ABF-B728-E8A4-B25E-0951C1793724}" src="https://user-images.githubusercontent.com/85773014/121761734-18500e80-cb64-11eb-97b5-35530c2b9f35.png">

but when combile , i got lots errors
<img width="835" alt="{740247B1-5076-90C9-111A-DB854F2D7F40}" src="https://user-images.githubusercontent.com/85773014/121761720-feaec700-cb63-11eb-95ea-7e359efe6287.png">

- Unity version: 2021.1.17f1
- Platform:  IOS
- Device: iphoneX  ios14.5 , macbook macos10.15.4,  XCode 12.3
- How did you download the plugin: from github

First, I have tried old version plugins that it used NativeGallery.cs，but XCode also report lots Error like above.
then i find the newest on github,but it didnt work.
i think there is something i did't know ,for this is the second time i work unity on ios.
hope you can help me ,thank you!!!

**Comment by yasirkula** [comment]
Did you add `insert -framework MobileCoreServices -framework ImageIO` to both **Unity-iPhone** Target and **UnityFramework** Target? If possible, I'd suggest using automated setup.

**Comment by Akira8707** [comment]
thanks for your helping, it is solved by insert -framework MobileCoreServices -framework ImageIO to UnityFramework Target
