### ISSUE TITLE
"Deleting gallery item" message keeps appearing in log

### ISSUE THREAD

**Issue by naskardebadri** [yasirkula/UnityNativeCamera#7]
Whenever I click a picture with my Android device's default camera, the following message appears in logcat:
`Deleting gallery item: /storage/emulated/0/DCIM/Camera/IMG_20180907_184429747.jpg`
And then the path of the image is not getting printed which I had logged for in my code.
However if I use any other camera app other than the default one, the task is getting completed as expected and printing the path in log.
Please help me with this.

**Comment by yasirkula** [comment]
As far as I understand, NativeCamera prompts you to choose a camera app for taking the picture. This actually shouldn't happen and the default camera app should be used automatically, so it was kind of surprising to hear for me :)

Regardless of that side note, `Deleting gallery item:` message appears when the camera application saves  a copy of the image to the gallery. In this case, the copy in the gallery [is deleted](https://github.com/yasirkula/UnityNativeCamera/blob/dcaf893b59658cba669d36b419bc558ba94f094d/JAR%20Source/NativeCameraPictureFragment.java#L173). But I can't really say why the path of the final image is not logged in the callback function. I've never encountered this issue myself. Is it a consistent behaviour across different devices/emulators?
