### ISSUE TITLE
Is there a way to make it take a photo without user input?

### ISSUE THREAD

**Issue by damonftl** [yasirkula/UnityNativeCamera#71]
I need to be able to take the photos without the user having to push whatever they need to in the phone's camera app. That is, the user can push a button in my app, then the camera opens and takes a series of photos automatically, maybe two per second, and then the camera closes and they are back in my app again.

Is this at all possible? I have the UnityNativeCamera code working fine on a phone already, so I know that is all set. I saw on another issue (https://github.com/yasirkula/UnityNativeCamera/issues/39#issue-657276246) a person successfully making the app take a series of shots, but in that case the user has to push the button on the phone to actually take each photo. I'm trying to make it take the photos without user input. Thank you for any help!

**Comment by yasirkula** [comment]
This is unfortunately not possible with NativeCamera. You will probably need a solution like this: https://assetstore.unity.com/packages/tools/integration/natdevice-media-device-api-162053. I don't know if there are any free solutions for this.
