### ISSUE TITLE
Is there any way to record a video without sound?

### ISSUE THREAD

**Issue by RobinReiner** [yasirkula/UnityNativeCamera#76]
Hello,
thank you for the development of UnityNativeCamera. Is there any way to mute the recorded video by an option before or after recording?
We have an use case where we don't want to record the audio.

Thanks

**Comment by yasirkula** [comment]
On which platforms do you want this feature?

**Comment by RobinReiner** [comment]
Our application runs on android, ios and windows. For windows, we use a different plugin for recording, but it doesn't have the feature on board either.

**Comment by yasirkula** [comment]
This plugin uses ACTION_VIDEO_CAPTURE Intent on Android and UIImagePickerController class on iOS. I've googled your issue for each platform. I've come to the conclusion that the only reliable way to achieve this is to strip the video's audio AFTER it is recorded by post-processing the video.

Here are some native solutions:

- Android: everyone agrees that it requires using ffmpeg wrappers on Android
- iOS: https://stackoverflow.com/questions/40194128/remove-audio-from-a-video-file?rq=1

I unfortunately won't be adding this feature.

**Comment by RobinReiner** [comment]
Thank you for the support and the quick feedback. Understandable, thought there may already be a way natively.
Kind Regards
