### ISSUE TITLE
Use with Gallery

### ISSUE THREAD

**Issue by kadirmenz** [yasirkula/UnityNativeCamera#81]
Hi,
I also use your UnityNativeGallery, I need to create 2 buttons which are Take From Camera and Select From Gallery but I wanna make them in just one button. I mean I want that when I click upload picture button, standart view of this functionality(upload picture from gallery/camera) appear which ask us select from gallery or from camera. I would like to hear your ideas?

**Comment by yasirkula** [comment]
My plugins doesn't provide a native UI for this selection, unfortunately. The easiest solution would be to create these buttons with Unity's UI system. Or, you can use a 3rd-party plugin which allows displaying native dialogs to the user.

**Comment by kadirmenz** [comment]
Thank you for your information, let me do it via Unity UI
