### ISSUE TITLE
iOS 14.6 - iPad 11.6

### ISSUE THREAD

**Issue by marcolbx** [yasirkula/UnityNativeCamera#83]
**Description of the bug**

Video recording does not work, the camera is always black for this specs specifically iPad 11.6-iOS 14.6. 
On iPad 7 and iOS 14.5 it works

**Reproduction steps**
Just plug the example script of this plugin and create a button to record the video, the video path was null: 
```
public void RecordVideo()
{
	NativeCamera.Permission permission = NativeCamera.RecordVideo( ( path ) =>
	{
		Debug.Log( "Video path: " + path );
		if( path != null )
		{
			// Play the recorded video
			Handheld.PlayFullScreenMovie( "file://" + path );
		}
	} );

	Debug.Log( "Permission result: " + permission );
}
```
**Additional info**
The taking picture method did worked. 

**Platform specs**
- Unity version: *e.g. 2020.3.22f1*
- Platform: iOS 14.6 - iPad 11.6

**Comment by yasirkula** [comment]
It may also be a Handheld.PlayFullScreenMovie issue. Can you try using a VideoPlayer? Or you can also try NativeCamera.GetVideoThumbnail.

**Comment by marcolbx** [comment]
Apparently it did work but for some exception it did not work while testing. I am closing this issue
