### ISSUE TITLE
Possibility of accessing variable framerate capture modes

### ISSUE THREAD

**Issue by dustinkerstein** [yasirkula/UnityNativeCamera#9]
_This is most definitely a feature request. Not sure where you want these posted._

I'm looking to access 60fps and higher framerates on devices that support them (at whatever resolution/framerate combo is valid). Are there any plans for adding this support? Would anyone be interested in a bounty for adding it?

Thanks!

**Comment by yasirkula** [comment]
On iOS, UIImagePickerController should be replaced with AVFoundation to support setting the frame rate.

Currently, I'm not interested in a bounty for this feature request, sorry.

**Comment by dustinkerstein** [comment]
K, thanks.

**Comment by dustinkerstein** [comment]
FYI I was able to force a higher FPS capture on Android by installing another camera app and setting it as the default camera app - I'm not entirely sure that's supposed to be allowed per your comment in #7 but it does seem to work :)

**Comment by yasirkula** [comment]
NativeCamera uses the default camera app, so this behaviour is normal :) It is up to the camera application to respect the time limit etc. parameters, though.
