### ISSUE TITLE
How to save taken Pictures and recorded videos using Native Camera & Native Gallery Plugins?

### ISSUE THREAD

**Issue by UnityQueriesAsk** [yasirkula/UnityNativeCamera#91]
Hi @yasirkula, Thank you so much for this Plugin. I am using this Plugin in my application and the application is able to access the device's native camera. I am also able to take pictures and record videos but these are not saved in Gallery.

I have checked the Native Gallery for Android & iOS Plugin for saving the pictures and videos in Gallery.

Can you please help me with how can I save the taken pictures and recorded videos in Gallery using the Native Camera for Android & iOS and Native Gallery for Android & iOS Plugins so that I have to share those through the social media applications.

Thanks in advance.

**Comment by yasirkula** [comment]
You can call NativeGallery.SaveImageToGallery or SaveVideoToGallery with the path returned by NativeCamera. To share an image/video from within Unity, you can use Native Share for Android & iOS.

**Comment by yasirkula** [comment]
DateTime.ToString() could output invalid filename characters. Try my_fileTransfer.png. pathLocal doesn't have to be a raw filepath, it can even be null. If you're relying on it, I'd recommend not to.

**Comment by dramdani** [comment]
> DateTime.ToString() could output invalid filename characters. Try my_fileTransfer.png. pathLocal doesn't have to be a raw filepath, it can even be null. If you're relying on it, I'd recommend not to.

thanks it work.
