### ISSUE TITLE
Permission Denied on iOS with no Popup

### ISSUE THREAD

**Issue by kidproquo** [yasirkula/UnityNativeCamera#94]
**Description of the bug**
This is a great plugin. Thanks for making it free!

I am using the code based on README:

```
NativeCamera.Permission permission = NativeCamera.TakePicture((path) =>
    {
      Debug.Log("Image path: " + path);
      if (path != null)
      {
        // Create a Texture2D from the captured image
        Texture2D texture = NativeCamera.LoadImageAtPath(path, maxSize);
        if (texture == null)
        {
          Debug.Log("Couldn't load texture from " + path);
          return;
        }
        SentenceImg.sprite = Sprite.Create(texture, new Rect(0, 0, texture.width, texture.height), new Vector2(0.5f, 0.5f));
        PhotoPath = path;
      }
    }, maxSize);

    Debug.Log("Permission result: " + permission);
```

No popup is shown asking for the permission. Debug log shows `Persmission result: Denied`.

**Platform specs**

Please provide the following info if this is a Unity 3D repository.

- Unity version: *2021.3.4f1*
- Platform: *iOS*
- Device: *iPad (6th Generation), iOS 14.6*
- How did you download the plugin: *Asset Store, latest release*

**Additional info**
Player settings:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/410966/180314706-76977af9-657d-424d-a219-8fda36c2a584.png">

Info.plist with permission string:

<img width="862" alt="image" src="https://user-images.githubusercontent.com/410966/180314591-db087561-fd9a-461a-b5d5-87011353c1bb.png">

Please check Logcat (Android) or Xcode console (iOS) for any meaningful error messages and include them here.
```
Permission result: Denied
SentencePopup:TakePicture(Int32)
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()
```

**Comment by kidproquo** [comment]
Some more updates:

- Tried on Android, Pixel 5A. Works with no issues - permission popup appears and I can successfully take pics
- Tried manual setup in iOS. Same issue. No popup and I get the `Denied` debug log

**Comment by BenIVRE** [comment]
If you've tested it once and chose to deny permissions, iOS will always remember that. You need to reset all permissions on the device if you want to test different flows.

**Comment by yasirkula** [comment]
@kidproquo May it really be the case? Can you uninstall the app and then reinstall it from scratch?

**Comment by kidproquo** [comment]
I have never seen the pop-up to choose Deny. Let me try a different build ID and/or identifier.

**Comment by kidproquo** [comment]
Ok, that fixed it. Deleted app and reinstalled. Got the popup. Closing issue. Thanks.

**Comment by yasirkula** [comment]
Happy to hear that!
